indicators_rename = {
    "Population, ages 0-14 (% of total)": "population_0_14_percent",
    "Population, ages 15-64 (% of total)": "population_15_64_percent",
    "Population ages 65 and above (% of total)": "population_65_plus_percent",
    "Population, female (% of total)": "female_population_percent",
    "Population, total": "total_population",
    "Rural population (% of total population)": "rural_population_percent",
    "Population in largest city": "population_largest_city",
    "GDP growth (annual %)": "gdp_growth_annual_percent",
    "Surface area (sq. km)": "surface_area",
    "Population density (people per sq. km of land area)": "population_density",
    "Electricity production from renewable sources, excluding hydroelectric (% of total)": "elec_energy_prod_renewable_percent",
    "Electricity production from oil, gas and coal sources (% of total)": "elec_energy_prod_oil_gas_coal_percent",
    "Electricity production from nuclear sources (% of total)": "elec_energy_prod_nuclear_percent",
    "Electricity production from natural gas sources (% of total)": "elec_energy_prod_naturalgas_percent",
    "Electricity production from hydroelectric sources (% of total)": "elec_energy_prod_hydroelectric_percent",
    "Electric power consumption (kWh per capita)": "elect_consumption_Kwh_per_capita",
    "Access to electricity (% of population)": "elect_access_percent_population"
}

countries_to_remove = [
    "High income: nonOECD",
    "High income: OECD",
    "OECD members",
    "Other small states",
    "Low income",
    "Lower middle income",
    "Low & middle income",
    "Middle East & North Africa (all income levels)",
    "Middle income",
    "Middle East & North Africa (developing only)",
    "Latin America & Caribbean (all income levels)",
    "Upper middle income",
    "World",
    "South Asia",
    "Sub-Saharan Africa (developing only)",
    "Sub-Saharan Africa (all income levels)",
    "Small states",
    "Least developed countries: UN classification",
    "Central Europe and the Baltics",
    "East Asia & Pacific (developing only)",
    "East Asia & Pacific (all income levels)",
    "Europe & Central Asia (all income levels)",
    "Arab World",
    "Europe & Central Asia (developing only)",
    "Heavily indebted poor countries (HIPC)",
    "Latin America & Caribbean (developing only)",
    "Fragile and conflict affected situations",
    "High income",
    "European Union",
    "North America",
    "Euro area"
]